# Generated by Django 4.1.7 on 2023-03-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=30)),
                ('lastname', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('comment', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
