# Generated by Django 4.1.7 on 2023-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('mobile', models.TextField(max_length=15)),
                ('password', models.TextField(max_length=25)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
