# Generated by Django 4.1.7 on 2023-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_alter_register_email_alter_register_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
