# Generated by Django 4.1.7 on 2023-05-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_alter_register_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_admin',
            field=models.BooleanField(),
        ),
    ]
