# Generated by Django 4.1.7 on 2023-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_alter_register_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('cost', models.TextField()),
                ('photo', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
