# Generated by Django 4.1.7 on 2023-05-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0015_alter_items_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
