# Generated by Django 4.1.7 on 2023-05-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0019_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photo',
        ),
    ]
