# Generated by Django 4.1.7 on 2023-05-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0021_products_delete_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
