# Generated by Django 4.1.7 on 2023-05-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0025_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
